### PR TITLE
Db migrations

### LINKED ISSUE #124: DB migrations (reset) mechanism
We should support versioning the database (similarly to how it's done with Realm in the apps), to at least reset it when the version is updated.

Current context: The TCNs table is getting new columns in 0.4, which will make the app crash for users updating from 0.3. 

We can alternatively tell the testers to delete and reinstall the app, but this is not ideal.

### PR DESCRIPTION
**Pull request by duskoo**

### CODE REVIEW

File: src/dependencies.rs [hunk 1]
```diff
@@ -124,7 +129,8 @@ pub fn dependencies() -> &'static Dependencies<
 }
 
 fn create_dependencies(
-    sqlite_path: &str,
+    database: Arc<Database>,
```
Comment (duskoo) [inline src/dependencies.rs:132]: changed api

File: src/dependencies.rs [hunk 2]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
+        assert_eq!(1, new_db_version);
+
+        let columns_6 = core_table_info("tcn", database.clone());
+        assert_eq!(6, columns_6.len());
+
+    }
+
+    fn prep_data_03(database: Arc<Database>){
+
+        let exported_db_sql = "BEGIN TRANSACTION;
```
Comment (duskoo) [inline src/dependencies.rs:236]: db exported from android app

File: src/database/migration.rs [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+            .unwrap();
+        self.database
+            .execute_sql(
+                "alter table tcn add column contact_end integer not null default 0;",
+                params![],
+            )
+            .unwrap();
+        self.database
+            .execute_sql(
+                "alter table tcn add column min_distance real default 32.0;",
```
Comment (duskoo) [inline src/database/migration.rs]: which default values to use?

File: src/database/database.rs [hunk 4]
```diff
@@ -20,6 +20,30 @@ impl Database {
...
         conn.execute(sql, pars)
     }
+    #[allow(dead_code)]
+    pub fn execute_batch(&self, sql: &str) -> Result<()> {
+        let res = self.conn.lock();
+        let conn = expect_log!(res, "Couldn't lock mutex");
+        conn.execute_batch(sql)
+    }
+
+    pub fn core_pragma_query(&self, pragma_variable_name: &str) -> i32 {
```
Comment (ivnsch) [inline src/database/database.rs]: Why are we assuming that pragma is always an int?

File: src/database/database.rs [hunk 5]
```diff
@@ -20,6 +20,30 @@ impl Database {
...
+        let res = self.conn.lock();
+        let conn = expect_log!(res, "Couldn't lock mutex");
+        let mut value = 0;
+        let _ = conn.pragma_query(None, pragma_variable_name, |row| {
+            let value_res = row.get(0);
+            value = value_res.unwrap();
```
Comment (ivnsch) [inline src/database/database.rs]: Use `expect_log` instead of `unwrap`, as Android doesn't see std out/err so we'd not know what crashed.

File: src/database/database.rs [hunk 6]
```diff
@@ -20,6 +20,30 @@ impl Database {
...
+            Ok(())
+        });
+        value
+    }
+
+    pub fn core_pragma_update(&self, pragma_variable_name: &str, new_value: &i32) {
+        let res = self.conn.lock();
+        let conn = expect_log!(res, "Couldn't lock mutex");
+        let _ = conn.pragma_update(None, pragma_variable_name, new_value);
```
Comment (ivnsch) [inline src/database/database.rs]: Assuming this `_` is a `Result`, the error case should be handled (with at least `expect_log`).

File: src/database/migration.rs (hunk 3 above)
Comment (ivnsch) [reply src/database/migration.rs]: I believe we agreed on clearing the database. Aside that it's simpler, it seems correct here. Setting default values is basically lying as we haven't measured this and will be probably confusing too.

File: src/database/migration.rs [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+    pub fn new(database: Arc<Database>) -> Migration {
+        Migration { database: database }
+    }
+
+    pub fn run_db_migrations(&self, required_db_version: i32) {
+        let pragma_variable_name = "user_version";
+        let mut db_version = self.database.core_pragma_query(pragma_variable_name);
+        while db_version < required_db_version {
+            match db_version {
+                0 => {
```
Comment (ivnsch) [inline src/database/migration.rs:38]: Maybe sync this with the migration index used in the function's name (i.e. use here `3`)?

File: src/database/migration.rs [hunk 8]
```diff
@@ -0,0 +1,65 @@
+use super::database::Database;
+use rusqlite::{params};
+use std::sync::Arc;
+
+pub struct Migration {
+    database: Arc<Database>,
+}
+
+impl Migration {
+    pub fn migrate_data_03_to_04(&self) {
```
Comment (ivnsch) [inline src/database/migration.rs]: This shouldn't be `pub`. I'd also move it below the pub methods.

File: src/database/migration.rs [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+        Migration { database: database }
+    }
+
+    pub fn run_db_migrations(&self, required_db_version: i32) {
+        let pragma_variable_name = "user_version";
+        let mut db_version = self.database.core_pragma_query(pragma_variable_name);
+        while db_version < required_db_version {
+            match db_version {
+                0 => {
+                    println!("db version is 0");
```
Comment (ivnsch) [inline src/database/migration.rs]: Remove prints, use log instead, if needed.

File: src/database/migration.rs [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+                    self.migrate_data_03_to_04();
+                    db_version += 1;
+                }
+                _ => {println!("db ver is incorrect");
```
Comment (ivnsch) [inline src/database/migration.rs]: Error handling should be improved: when can this happen? If it shouldn't happen, use `expect_log`

File: src/database/migration.rs [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    pub fn new(database: Arc<Database>) -> Migration {
+        Migration { database: database }
+    }
+
+    pub fn run_db_migrations(&self, required_db_version: i32) {
+        let pragma_variable_name = "user_version";
+        let mut db_version = self.database.core_pragma_query(pragma_variable_name);
+        while db_version < required_db_version {
```
Comment (ivnsch) [inline src/database/migration.rs]: 👍

File: src/dependencies.rs [hunk 12]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use rusqlite::{params, Row};
+
+
+    #[test]
+    fn test_create_dependencies_with_migration_from_03_to_04(){
+        let database = Arc::new(Database::new(
+        //   Connection::open("./testdb2-copy.sqlite").expect("Problem opening db"),
```
Comment (ivnsch) [inline src/dependencies.rs]: Remove

File: src/dependencies.rs [hunk 13]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
+        let db_version = database.core_pragma_query(pragma_variable_name);
+
+        assert_eq!(0, db_version);
+
+        create_dependencies(database.clone(), 3);
+
+        let new_db_version = database.core_pragma_query(pragma_variable_name);
+        assert_eq!(1, new_db_version);
+
+        let columns_6 = core_table_info("tcn", database.clone());
```
Comment (ivnsch) [inline src/dependencies.rs]: By convention, let's use `clone()` only if required by the compiler.

File: src/dependencies.rs [hunk 14]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
     }
 }
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use rusqlite::{params, Row};
+
+
+    #[test]
+    fn test_create_dependencies_with_migration_from_03_to_04(){
```
Comment (ivnsch) [inline src/dependencies.rs:213]: Why is this testing `create_dependencies`? I'd expect this test to touch only the migration component and be in migration.rs.

File: src/dependencies.rs [hunk 15]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
         alert_dao,
     }
 }
+#[cfg(test)]
```
Comment (ivnsch) [inline src/dependencies.rs:206]: Should be in migration.rs

File: src/dependencies.rs [hunk 16]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
+mod tests {
```
Comment (ivnsch) [inline src/dependencies.rs:207]: Can we add more tests, in particular of generic parts like checking that setting pragma works, that migrating to an older version fails, that migration to the same version does nothing, etc...

File: src/dependencies.rs [hunk 17]
```diff
@@ -199,3 +203,85 @@ fn create_dependencies(
...
+
+        assert_eq!(0, db_version);
+
+        create_dependencies(database.clone(), 3);
+
+        let new_db_version = database.core_pragma_query(pragma_variable_name);
+        assert_eq!(1, new_db_version);
+
+        let columns_6 = core_table_info("tcn", database.clone());
+        assert_eq!(6, columns_6.len());
```
Comment (ivnsch) [inline src/dependencies.rs:230]: This test is very lightweight. But ok, this specific migration is more a proof of concept.

**Review by ivnsch — CHANGES_REQUESTED** [review]

**Comment by ivnsch** [comment]
I assume that you're able to adjust Android? Otherwise I can take this over after the review is addressed.

File: src/database/migration.rs (hunk 3 above)
Comment (ivnsch) [reply src/database/migration.rs]: Anyway, since the solution is already in place, I'd just drop and create the TCN table here.

File: src/database/database.rs [hunk 18]
```diff
@@ -20,6 +20,30 @@ impl Database {
...
+    pub fn execute_batch(&self, sql: &str) -> Result<()> {
+        let res = self.conn.lock();
+        let conn = expect_log!(res, "Couldn't lock mutex");
+        conn.execute_batch(sql)
+    }
+
+    pub fn core_pragma_query(&self, pragma_variable_name: &str) -> i32 {
+        let res = self.conn.lock();
+        let conn = expect_log!(res, "Couldn't lock mutex");
+        let mut value = 0;
```
Comment (ivnsch) [inline src/database/database.rs]: This construct seems weird. Can't we have `pragma_query` returning the value in the result and use that?

File: src/database/database.rs (hunk 4 above)
Comment (duskoo) [reply src/database/database.rs]: user_version is an int, so I took the shortcut. 
Screen Shot 2020-08-03 at 6 35 17 PM

I propose we open a new ticket if other pragmas will be needed.

File: src/database/database.rs (hunk 5 above)
Comment (duskoo) [reply src/database/database.rs]: Ok.

File: src/database/database.rs (hunk 6 above)
Comment (duskoo) [reply src/database/database.rs]: Ok. Will add fixes tonight.

File: src/database/migration.rs (hunk 8 above)
Comment (duskoo) [reply src/database/migration.rs]: Ok

File: src/database/migration.rs (hunk 3 above)
Comment (duskoo) [reply src/database/migration.rs]: Ok

File: src/database/migration.rs (hunk 7 above)
Comment (duskoo) [reply src/database/migration.rs:38]: Default value of user_version pragma is 0: this will be reported by sqlite when queried.
So app version 0.3 has user_version 0 (this can not be changed)
app version 0.4 will have user_version 1 (this can be adjusted - ie. we can set user_version = 4)

File: src/database/migration.rs (hunk 9 above)
Comment (duskoo) [reply src/database/migration.rs]: Ok

File: src/dependencies.rs (hunk 16 above)
Comment (duskoo) [reply src/dependencies.rs:207]: Add more granular tests - ok

File: src/dependencies.rs (hunk 14 above)
Comment (duskoo) [reply src/dependencies.rs:213]: This is effectively an integration test: making sure that bootstrap will succeed after app update from 0.3 to 0.4.
I would like to leave it here, and add granular tests to Migration. 
Thoughts?

**Comment by duskoo** [comment]
> I assume that you're able to adjust Android? Otherwise I can take this over after the review is addressed.

Yes, I should be fine. I will ping you with the status by end of business today.

File: src/database/database.rs (hunk 18 above)
Comment (duskoo) [reply src/database/database.rs]: Result<T, Error> ?
Will check.

File: src/database/migration.rs (hunk 7 above)
Comment (ivnsch) [reply src/database/migration.rs:38]: Right. Use the database numbers in the function name, then? The migration is 0 -> 1, strictly speaking.

File: src/dependencies.rs (hunk 14 above)
Comment (ivnsch) [reply src/dependencies.rs:213]: The test feels vague to me. If it's testing that `create_dependencies` executes migrations, it should be more generic. If it's testing that 03->04 (0->1) works, it should test the complete migration, and be in migration.rs.

**Comment by duskoo** [comment]
> > I assume that you're able to adjust Android? Otherwise I can take this over after the review is addressed.
> 
> Yes, I should be fine. I will ping you with the status by end of business today.

@i-schuetz Most of the issues have been fixed. If there are urgent changes to be made, please take over the PR. I will be available on Wednesday at earliest.

**Review by ivnsch — APPROVED** [review]

File: src/dependencies.rs (hunk 14 above)
Comment (ivnsch) [reply src/dependencies.rs:213]: Approving, but suggestion here is to make this test generic (you can do this post-merge if you want). It's better to do something small, like adding a dummy column. Then you can also remove the long SQL script from dependencies.rs.
